// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lectuphndieqxoluyhkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlY3R1cGhuZGllcXhvbHV5aGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjY3NzQsImV4cCI6MjA2MzY0Mjc3NH0.oEJHEnVOHD5eJcrNF6tXtFmLEoZPXLQRWPa1DhoQuIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // We handle the OAuth/magic-link callback ourselves in src/main.tsx so
    // multiple consumers don't race over the same URL fragment (which was
    // leaving users without a session and looping them back to /login).
    detectSessionInUrl: false,
    flowType: 'implicit',
  }
});
