// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lectuphndieqxoluyhkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlY3R1cGhuZGllcXhvbHV5aGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjY3NzQsImV4cCI6MjA2MzY0Mjc3NH0.oEJHEnVOHD5eJcrNF6tXtFmLEoZPXLQRWPa1DhoQuIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);